In [1]:
import numpy as np
import pandas as pd

### Measure of Central Tendancy

In [31]:
# Mean
# Median
# Mode

In [2]:
data = [10, 20, 30, 40, 50]

In [3]:
data

[10, 20, 30, 40, 50]

In [4]:
# Mean

mean = sum(data) / len(data)
mean

30.0

In [5]:
arr = np.array(data)
arr

array([10, 20, 30, 40, 50])

In [7]:
print(arr.mean())

30.0

In [8]:
s = pd.Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
print(s.mean())

30.0

In [13]:
data

[10, 20, 30, 40, 50]

In [12]:
# Median

median = data[len(data) // 2]
median

30

In [33]:
s.median()

30.0

In [20]:
# Mode

data2 = [10, 20, 20, 20, 30, 30, 30, 40]
data2

[10, 20, 20, 20, 30, 30, 30, 40]

In [21]:
arr2 = pd.Series(data2)
arr2

0    10
1    20
2    20
3    20
4    30
5    30
6    30
7    40
dtype: int64

In [22]:
arr2.mode()

0    20
1    30
dtype: int64

In [24]:
mode = arr2.mode()[0]
print(mode)

20

In [25]:
import statistics

In [30]:
mode = statistics.mode(data2)
mode

20

### Measure of Dispersion

In [ ]:
# Range
# Variance
# Standard Deviation

In [34]:
data

[10, 20, 30, 40, 50]

In [35]:
# Range

range = max(data) - min(data)
range

40

In [36]:
# Variance

data

[10, 20, 30, 40, 50]

In [37]:
arr = np.array(data)
arr

array([10, 20, 30, 40, 50])

In [39]:
var = arr.var()
print(var)

200.0

In [41]:
# Standard Deviation

std = var ** 0.5
print(std)

14.142135623730951

In [43]:
std = arr.std()
print(std)

14.142135623730951